main:
  hosts:
    - home.ctptech.dev:
        hostname: 'home.ctptech.dev'
        override_hostname: 'ubuntu-server.local'
        password: 'NetTechScience99#!!$='
        username: 'ubuntuserver'
        http_scheme: 'https'
        http_port: 8443
        ssh_port: 22
    - aws.ctptech.dev:
        hostname: 'aws.ctptech.dev'
        private_key: '~/.ssh/ctptechfree1.aws.pem'
        username: 'ubuntu'
        http_scheme: 'https'
        http_port: 8443
    - vpn.ctptech.dev:
        hostname: 'vpn.ctptech.dev'
        private_key: '~/.ssh/google_compute_engine'
        username: 'charlieporth1_gmail_com'
        http_scheme: 'https'
        http_port: 8443